<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RDPCnC-CN</AssemblyName>
    <RootNamespace>RDPWrapCN</RootNamespace>
    <ApplicationManifest></ApplicationManifest>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>
</Project>
